### PR TITLE
Add ERD for the data architecture

### PR DESCRIPTION
**Pull request by pbkabali**
- Added diagram for data architecture and entity relations

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team! 🖥️ 👀 ✨ 

- Your ERD is mostly correct.
- Creative use of a 'dislike' button. Can't wait to see it working!

## However, some changes are still required... 🧰 🔨 🔧 

- The `docs` folder should be named `doc` instead. Please fix this.
- Your ERD is missing a `comments` table. Please add this!
- The rest of your tables seem to be in order!

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by pbkabali** [comment]
Thanks for the review @voscarmv. We really appreciate it. We have implemented the changes and requested another.

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 
## Great job guys :clap: :clap: :clap:, thanks for making the required changes.

now you can merge, your project is approved.

## Happy Coding :tophat:

**Comment by pbkabali** [comment]
Thank you for your review and time @elmejdki

**Pull request merged**
