### PR TITLE
Feature to optimize friendship association

### PR DESCRIPTION
**Pull request by alvp01**
This feature is intended to improve and optimize the friendships queries to make sure inverse relationships don't cause duplicated results.

### CODE REVIEW

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Require Changes :red_circle: 
### Hey guys! I hope you doing well. there are some things to improve before you get approved

- [ ] **Let's improve the way we list the the `current_user` friends**:
```ruby
# User Model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

# So we can call it now as current_user.friends
# I will let you think on your own how you can implement this method to get all the peding_firends
# If you need extra help let me know through slack
```
# Happy Coding! :nerd_face:

**Comment by pbkabali** [comment]
Thank you for your review @Dandush03. We have submitted another review request after following your advice to make changes. Thanks a lot

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Well done team! You have met this milestone's requirements. Nice job implementing a comprehensive test suite! :+1: Keep up the good work!

__[Note]:__ Please remove the commented code from your `user` model file before merging your pull request. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

_Happy coding!_ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by pbkabali** [comment]
Thank you very much for the review, @trekab.

**Pull request merged**
