### PR TITLE
Implement friendship model and associations

### PR DESCRIPTION
**Pull request by pbkabali**
### What this PR does:
- Adds a Friendship model
- Adds friendship associations
- Adds friendship controllers and views
- Adds tests with Rspec

### CODE REVIEW

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Request Changes :red_circle: 

### Hey guys, you've done a fantastic job :muscle: 
__Be sure to fix all the issue commented below before submiting a new review__

- [ ] __You did a great job with your models but, in this milestone, you most implement does change into your views, be sure to add the followings:__
  -  - [x] User can invite friends 
  -  - [x] User can see friendships requests 
  -  - [x] User has to accept a friendship request to start a friendship
  -  - [x] User can reject a friendship request
  -  - [x] There is a button to invite the user to friendship on the user's list page and on the single-user page
  -  - [x] Posts timeline includes posts written by logged-in user and their friends 
- [x] __Each module, view, or controller should be tested as required before__

# Happy Coding :muscle: :computer:

**Comment by pbkabali** [comment]
Hi @Dandush03, thank you very much for your review. We have worked on the feedback and submitted another review request.

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required  🏗️ 🔨 
****
### Hello Team  👋 
You are doing a great job with this project! 👍 You are almost done! 💪 Great job applying the feedback you have received from the other TSE. 🎖️ 🌟 There are just a few small issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The user should be able to invite another user to be a friend. There is currently no link/ button to be able to add the user as a friend.
screenshot showing user show page 👇 
Screen Shot 2020-10-23 at 10 20 00 PM
 Screenshot showing all users page 👇 
Screen Shot 2020-10-23 at 10 19 05 PM

- [ ] Currently, the user can see posts by other users even if they are not friends with that user. 
 Screenshot  of Test's timeline below 👇 
Screen Shot 2020-10-23 at 10 27 24 PM


****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by pbkabali** [comment]
Thanks for the review, @BrittanyBlake. So we have already implemented the features you mentioned as can be seen in the screenshots below. Not sure why you are not getting them. 

- Friend request button on user's page
image

- Friend request link on all users page
image

- Timeline posts are only from current user and friends
image

Would you please kindly check again because we are testing everything okay locally. We have however removed the friend request link for the logged-in user.

Thanks

**Review by rOluochKe — APPROVED** [review]
Hello Team
### You got it, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one. 
- Happy coding!

**Comment by pbkabali** [comment]
Thank you so much for your time, @rOluochKe.

**Pull request merged**
